import {
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGOUT_REQUEST,
  LOGOUT_SUCCESS,
  REGISTER_REQUEST,
  REGISTER_SUCCESS,
  REGISTER_FAILURE,
  CLEAR_ERROR,
} from './auth/authActionTypes';
import {
  loginUser,
  registerUserSekolah,
  logoutUser,
  loginRequest,
  loginSuccess,
  loginFailure,
  registRequest,
  registSuccess,
  registFailure,
  logoutRequest,
  logoutSuccess,
  clearError,
} from './auth/auth';
import { SET_MESSAGE, CLEAR_MESSAGE } from './alert/alertActionTypes';
import {
  GET_TINGKATAN_REQUEST,
  GET_TINGKATAN_SUCCESS,
  GET_TINGKATAN_FAILURE,
  CLEAR_TINGKATAN_DATA,
  POST_TINGKATAN_REQUEST,
  PUT_TINGKATAN_REQUEST,
  DEL_TINGKATAN_REQUEST,
  POST_TINGKATAN_SUCCESS,
  POST_TINGKATAN_FAILURE,
} from './tingkatan/tingkatanActionTypes';
import { setMessage, clearMessage, timedMessage } from './alert/alert';
import {
  getDataTingkatan,
  getTingkatanRequest,
  getTingkatanSuccess,
  getTingkatanFailure,
  clearTingkatanData,
  postDataTingkatan,
  postTingkatanRequest,
  postTingkatanSuccess,
  postTingkatanFailure,
} from './tingkatan/tingkatan';

export {
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGOUT_REQUEST,
  LOGOUT_SUCCESS,
  loginUser,
  registerUserSekolah,
  logoutUser,
  loginRequest,
  loginSuccess,
  loginFailure,
  registRequest,
  registSuccess,
  registFailure,
  logoutRequest,
  logoutSuccess,
  REGISTER_REQUEST,
  REGISTER_SUCCESS,
  REGISTER_FAILURE,
  CLEAR_ERROR,
  clearError,
  SET_MESSAGE,
  CLEAR_MESSAGE,
  setMessage,
  clearMessage,
  timedMessage,
  GET_TINGKATAN_REQUEST,
  GET_TINGKATAN_SUCCESS,
  GET_TINGKATAN_FAILURE,
  CLEAR_TINGKATAN_DATA,
  POST_TINGKATAN_REQUEST,
  PUT_TINGKATAN_REQUEST,
  DEL_TINGKATAN_REQUEST,
  POST_TINGKATAN_SUCCESS,
  POST_TINGKATAN_FAILURE,
  getDataTingkatan,
  getTingkatanRequest,
  getTingkatanSuccess,
  getTingkatanFailure,
  clearTingkatanData,
  postDataTingkatan,
  postTingkatanRequest,
  postTingkatanSuccess,
  postTingkatanFailure,
};
