// Auth Action Types
export const GET_TINGKATAN_REQUEST = 'GET_TINGKATAN_REQUEST';
export const GET_TINGKATAN_SUCCESS = 'GET_TINGKATAN_SUCCESS';
export const GET_TINGKATAN_FAILURE = 'GET_TINGKATAN_FAILURE';
export const CLEAR_TINGKATAN_DATA = 'CLEAR_TINGKATAN_DATA';

export const POST_TINGKATAN_REQUEST = 'POST_TINGKATAN_REQUEST';
export const PUT_TINGKATAN_REQUEST = 'PUT_TINGKATAN_REQUEST';
export const DEL_TINGKATAN_REQUEST = 'DEL_TINGKATAN_REQUEST';
export const POST_TINGKATAN_SUCCESS = 'POST_TINGKATAN_SUCCESS';
export const POST_TINGKATAN_FAILURE = 'POST_TINGKATAN_FAILURE';
